/* Auto-generated by PUYA MCU PIN CONFIGURATOR */
#ifndef __INIT_H
#define __INIT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* Peripheral handle externs */
extern TIM_HandleTypeDef htim1;

/* Function prototypes */
void APP_SystemClockConfig(void);
void APP_GpioConfig(void);
void Error_Handler(void);

#ifdef __cplusplus
}
#endif

#endif /* __INIT_H */

